# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange
import hashlib
import math
from ccxt.base.errors import ExchangeError
from ccxt.base.errors import ArgumentsRequired
from ccxt.base.errors import OrderNotFound


class coineal(Exchange):

    def describe(self):
        return self.deep_extend(super(coineal, self).describe(), {
            'id': 'coineal',
            'name': 'Coineal',
            'countries': ['US'],
            'version': 'v1',
            'rateLimit': 1000,
            'has': {
                'createMarketOrder': False,
                'fetchOrder': True,
                'fetchOrders': True,
                'fetchOpenOrders': True,
                'fetchCurrencies': False,
                'fetchTicker': True,
                'fetchTickers': False,
                'fetchOHLCV': False,
                'fetchOrderBook': True,
                'fetchTrades': False,
            },
            'urls': {
                'api': {
                    'public': 'https://exchange-open-api.coineal.com/open/api',
                    'private': 'https://exchange-open-api.coineal.com/open/api',
                },
                'www': 'https://www.coineal.com',
                'doc': [
                    'https://www.coineal.com/static-page/api/en_US/api.html',
                ],
                'fees': '',
            },
            'api': {
                'public': {
                    'get': [
                        'get_ticker',
                        'market_dept',
                        'common/symbols',
                    ],
                },
                'private': {
                    'get': [
                        'account/info',
                    ],
                },
            },
            'fees': {
                'trading': {
                    'maker': 0.09,
                    'taker': 0.12,
                },
            },
        })

    def fetch_markets(self, params={}):
        # {
        #     "symbol": "btcusdt",
        #     "count_coin": "usdt",
        #     "amount_precision": 5,
        #     "base_coin": "btc",
        #     "price_precision": 2
        # },
        response = self.publicGetCommonSymbols(params)
        result = []
        for i in range(0, len(response['data'])):
            market = response['data'][i]
            baseId = self.safe_string(market, 'base_coin')
            quoteId = self.safe_string(market, 'count_coin')
            base = self.safe_currency_code(baseId)
            quote = self.safe_currency_code(quoteId)
            id = base + quote
            symbol = base + quote
            precision = {
                'amount': self.safe_integer(market, 'amount_precision'),
                'price': self.safe_integer(market, 'price_precision'),
            }
            result.append({
                'id': id.lower(),
                'symbol': symbol.lower(),
                'base': base,
                'quote': quote,
                'baseId': baseId,
                'quoteId': quoteId,
                'active': True,
                'precision': precision,
                'limits': {
                    'amount': {
                        'min': None,
                        'max': None,
                    },
                    'price': {
                        'min': math.pow(10, -precision['price']),
                        'max': None,
                    },
                    'cost': {
                        'min': None,
                        'max': None,
                    },
                },
                'info': market,
            })
        return result

    def fetch_ticker(self, symbol, params={}):
        self.load_markets()
        timestamp = self.milliseconds()
        request = self.extend({
            'symbol': symbol,
        }, params)
        response = self.publicGetGetTicker(request)
        ticker = self.safe_value(response, 'data')
        return {
            'symbol': symbol,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'high': self.safe_float(ticker, 'high'),
            'low': self.safe_float(ticker, 'low'),
            'bid': self.safe_float(ticker, 'buy'),
            'bidVolume': None,
            'ask': self.safe_float(ticker, 'sell'),
            'askVolume': None,
            'vwap': None,
            'previousClose': None,
            'open': None,
            'close': None,
            'last': self.safe_float(ticker, 'last'),
            'percentage': None,
            'change': None,
            'average': None,
            'baseVolume': self.safe_float(ticker, 'vol'),
            'quoteVolume': None,
            'info': ticker,
        }

    def fetch_order_book(self, symbol, limit=None, params={}):
        self.load_markets()
        request = {
            'symbol': self.market_id(symbol),
            'type': 'step0',
        }
        if limit is not None:
            request['size'] = limit
        response = self.publicGetMarketDept(self.extend(request, params))
        data = self.safe_value(response, 'data')
        return self.parse_order_book(data.tick, data.tick.time, 'bids', 'asks')

    def fetch_balance(self, params={}):
        self.load_markets()
        query = self.omit(params, 'type')
        response = self.privateGetWalletBalance(query)
        balances = self.safe_value(response, 'data')
        wallets = self.safe_value(balances, 'WALLET')
        result = {'info': wallets}
        for i in range(0, len(wallets)):
            wallet = wallets[i]
            currencyId = wallet['coinType']
            code = self.safe_currency_code(currencyId)
            account = self.account()
            account['free'] = self.safe_float(wallet, 'available')
            account['total'] = self.safe_float(wallet, 'total')
            result[code] = account
        return self.parse_balance(result)

    def create_order(self, symbol, type, side, amount, price=None, params={}):
        self.load_markets()
        market = self.market(symbol)
        method = 'privatePostTradeOrderCreate'
        direction = side == 'BID' if 'buy' else 'ASK'
        request = {
            'amount': self.amount_to_precision(symbol, amount),
            'direction': direction,
            'pair': self.safe_string(market, 'id'),
            'price': self.price_to_precision(symbol, price),
        }
        response = getattr(self, method)(self.extend(request, params))
        return {
            'id': self.safe_value(response, 'data'),
            'info': response,
        }

    def cancel_order(self, id, symbol=None, params={}):
        self.load_markets()
        request = {
            'orderNo': id,
            'pair': self.market_id(symbol),
        }
        return self.privatePostTradeOrderCancel(self.extend(request, params))

    def fetch_open_orders(self, symbol=None, since=None, limit=None, params={}):
        if symbol is None:
            raise ArgumentsRequired(self.id + ' fetchOrders requires a symbol argument')
        self.load_markets()
        market = self.market(symbol)
        request = {
            'pair': self.safe_string(market, 'id'),
        }
        if limit is not None:
            request['size'] = limit
        response = self.privateGetTradeOrderListUnfinished(self.extend(request, params))
        result = self.safe_value(response, 'data')
        return self.parse_orders(self.safe_value(result, 'data'), market, since, limit)

    def fetch_order(self, id, symbol=None, params={}):
        self.load_markets()
        request = {
            'orderNo': id,
            'pair': self.market_id(symbol),
        }
        response = self.privateGetTradeOrderUnfinishedDetail(self.extend(request, params))
        data = self.safe_value(response, 'data')
        if not data:
            raise OrderNotFound(self.id + ' order ' + id + ' not found')
        return self.parse_order(data)

    def parse_order(self, order, market=None):
        marketName = self.safe_string(order, 'pair')
        market = market or self.findMarket(marketName)
        timestamp = self.safe_string(order, 'createdTime')
        if timestamp is not None:
            timestamp = int(round(float(timestamp)) * 1000)
        direction = self.safe_value(order, 'direction')
        side = direction == 'BUY' if 'BID' else 'SELL'
        amount = self.safe_float(order, 'totalAmount')
        fillAmount = self.safe_float(order, 'dealAmount', amount)
        remaining = amount - fillAmount
        return {
            'id': self.safe_string(order, 'id'),
            'datetime': self.iso8601(timestamp),
            'timestamp': timestamp,
            'lastTradeTimestamp': None,
            'status': None,
            'symbol': self.safe_string(market, 'symbol'),
            'side': side,
            'type': self.safe_string(order, 'orderType'),
            'price': self.safe_float(order, 'price'),
            'cost': None,
            'amount': amount,
            'filled': fillAmount,
            'remaining': remaining,
            'fee': None,
            'info': order,
        }

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        if method == 'GET':
            if query:
                url += '?' + self.urlencode(query)
        if api == 'private':
            self.check_required_credentials()
            query = self.urlencode(query)
            if method == 'POST':
                body = query
            secret = self.encode(self.secret)
            signature = self.hmac(query, secret, hashlib.sha256)
            headers = {
                'Cache-Control': 'no-cache',
                'Content-type': 'application/x-www-form-urlencoded',
                'X_ACCESS_KEY': self.apiKey,
                'X_SIGNATURE': signature,
            }
        return {'url': url, 'method': method, 'body': body, 'headers': headers}

    def handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody):
        httpCode = self.safe_integer(response, 'code', 200)
        if response is None:
            return
        if code >= 400:
            raise ExchangeError(self.id + ' HTTP Error ' + code + ' reason: ' + reason)
        if httpCode >= 400:
            message = self.safe_value(response, 'msg', '')
            raise ExchangeError(self.id + ' HTTP Error ' + httpCode + ' message: ' + message)
